services:
  templ:
    profiles: [hot]
    container_name: templ-container
    image: ghcr.io/a-h/templ:v0.3.1020
    working_dir: /app
    volumes:
      - "${PWD}:/app"
    command: ["generate", "--watch"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M

  tailwind:
    profiles: [hot]
    container_name: tailwind-container
    image: coutito/tailwindcss:v4.3.3
    volumes:
      - "${PWD}:/app"
    tty: true
    command: ["tailwindcss", "-i", "./assets/css/tailwind_input.css", "-o", "./assets/css/tailwind_styles.css", "--watch"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  hot:
    profiles: [hot]
    container_name: basement-container
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - "${PWD}:/app"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    depends_on:
      templ:
        condition: service_started
      tailwind:
        condition: service_started
