services:
  templ:
    profiles: [hot]
    container_name: templ-container
    image: ghcr.io/a-h/templ:v0.3.960
    working_dir: /app
    volumes:
      - "${PWD}:/app"
    command: ["generate", "--watch"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M

  tailwind:
    profiles: [hot]
    container_name: tailwind-container
    image: coutito/tailwindcss:v4.1.18
    volumes:
      - "${PWD}:/app"
    tty: true
    command: ["tailwindcss", "-i", "./assets/css/tailwind_input.css", "-o", "./assets/css/tailwind_styles.css", "--watch"]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M

  tailwind-minify:
    profiles: [build]
    container_name: tailwind-minify-container
    image: coutito/tailwindcss:v4.1.18
    volumes:
      - "${PWD}:/app"
    command: ["tailwindcss", "-i", "./assets/css/tailwind_input.css", "-o", "./assets/css/tailwind_styles.css", "--minify"]

  hot:
    profiles: [hot]
    container_name: basement-container
    image: cosmtrek/air
    environment:
      ENV: local
      AWS_PROFILE: ${AWS_PROFILE}
    working_dir: /app
    ports:
      - 3001:3000
    volumes:
      - "${PWD}:/app"
      - "~/.aws:/root/.aws:ro"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    networks:
      - emporium_network
    depends_on:
      templ:
        condition: service_started
      tailwind:
        condition: service_started

networks:
  emporium_network:     
    external: true         
    name: emporium_stg_network
