REMOTE_HOST = $$(aws ssm get-parameter \
		--name "/gureum/ssh/remote_host" \
		--query "Parameter.Value" \
		--output text \
		)

REMOTE_USER = $$(aws ssm get-parameter \
		--name "/gureum/ssh/remote_user" \
		--query "Parameter.Value" \
		--output text \
		)

PEM_KEY = $$(aws ssm get-parameter \
		--name "/gureum/ssh/pem_key" \
		--query "Parameter.Value" \
		--with-decryption \
		--output text \
		)

DOCKERHUB_TOKEN = $$(aws ssm get-parameter \
		--name "/dockerhub/token" \
		--query "Parameter.Value" \
		--with-decryption \
		--output text \
		)

