// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package landing_view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Bookmarks() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h2 id=\"videos\" class=\"heading-primary\">Videos</h2><ul class=\"w-full list-inside\"><li>[ ]  <a href=\"https://www.youtube.com/watch?v=z56jmr9z34q&amp;list=plyzovjj3bhqulokgg59rs43e29ro7i57j&amp;index=3\">★★★★★ | MIT CS Classes</a></li><li>[ ]  <a href=\"https://www.youtube.com/watch?v=HaBMAD-Dr8M&amp;list=PLnAxReCloSeTJc8ZGogzjtCtXl_eE6yzA\">★★★☆☆ | How Computers Work - Building Scott&#39;s CPU</a></li></ul><h2 id=\"full-blogs\" class=\"heading-primary\">Full Blogs</h2><h4 id=\"from-x\" class=\"heading-primary\">From X</h4><ul class=\"w-full list-inside\"><li><a href=\"https://graffioh.com/\">bertø (@graffioh)</a></li></ul><h4 id=\"from-college-material\" class=\"heading-primary\">From College Material</h4><ul class=\"w-full list-inside\"><li><a href=\"https://anishathalye.com/\">Anish Athalye (MIT)</a></li><li><a href=\"https://thesquareplanet.com/blog/\">Jon Gjengset (MIT)</a></li></ul><h4 id=\"from-others\">From Others</h4><ul class=\"w-full list-inside\" id=\"from-others-list\"><li><a href=\"https://graffioh.com/\">bertø (@graffioh)</a></li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
