// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package static_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import layouts_view "nugu.dev/basement/views/layouts"

func Reads() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"text-3xl font-semibold\">Papers / Articles / Books</h1><p>Some books that I already read / am reading / plan to read. The order doesn't matter, first doesn't mean best. The idea is to write something about them or post the exercises, but I need to organize everything first.</p><ul class=\"mt-5 w-full list-inside\"><li><span><a class=\"underline\" href=\"https://efrei.poupa.net/programmation%20en%20c/cours/the_c_puzzle_book.pdf\">The C puzzle book</a></span></li><li><span><a class=\"underline\" href=\"https://www.cis.upenn.edu/~cis5150/linalg-I-f.pdf\">Algebra for Computer Vision, Robotics, and Machine Learning</a></span></li><li><span><a class=\"underline\" href=\"https://jeffe.cs.illinois.edu/teaching/algorithms/\">Algorithms</a></span></li><li><span><a class=\"underline\" href=\"https://siboehm.com/articles/22/Fast-MMM-on-CPU\">Multidimensional Matrix Multiplication on CPU from Scratch</a></span></li><li><span><a class=\"underline\" href=\"https://people.freebsd.org/~lstewart/articles/cpumemory.pdf\">What every programmer should know about memory</a></span></li><li><span><a class=\"underline\" href=\"https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf\">MapReduce: Simplified Data Processing on Large Clusters</a></span></li><li><span><a class=\"underline\" href=\"https://raytracing.github.io/\">Ray tracing in one week</a></span></li><li><span>[112/495] Let's Go - Alex Edwards</span></li><li><span>Let's Go Further - Alex Edwards</span></li></ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts_view.StaticHome().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
