name: Deploy (production)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://basement.nugu.dev

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set SHORT_SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "coutito"
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build + push image to dockerhub
      run: |
        docker build \
          --build-arg BUILD_GOOS=linux \
          --tag coutito/basement-aws:prod-${{ env.SHORT_SHA }} \
          --target prod-final-bin .

        docker push coutito/basement-aws:prod-${{ env.SHORT_SHA }}

    - name: Deploy on production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull coutito/basement-aws:prod-${{ env.SHORT_SHA }}

          docker rm -f prod_basement || true

          docker run -d \
            --name prod_basement \
            -p 3001:5432 \
            -e ENV=prod  \
            coutito/basement-aws:prod-${{ env.SHORT_SHA }}
