name: Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-vars

    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v6
    - name: Add SHORT_SHA env property
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

    - name: Deploy to stage
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Deploying branch: ${{ env.BRANCH_NAME }}"
          echo "Deploying commit: ${{ env.SHORT_SHA }}"

          docker pull coutito/basement-aws:${{ env.SHORT_SHA }}
          docker run -d -p 3001:5432 coutito/basement-aws:${{ env.SHORT_SHA }}
